# -*- coding: utf-8 -*-
"""02_feature_extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zId-pOxJmk1GKULXjjOVP-77KUTFvkLV

# Data Loading
This section outlines the process of loading and preprocessing audio data for feature extraction. The goal is to prepare the audio for various machine learning models.

### Import Dependencies
This cell imports all necessary Python libraries for audio processing, deep learning models (TensorFlow and PyTorch), and utilities like `joblib` for data loading. Key libraries include `librosa` for audio manipulation, `tensorflow` for dataset creation, and `transformers` for pre-trained AST and Wav2Vec2 models.
"""

import os
import time
import joblib
import numpy as np
import librosa
import tensorflow as tf
import torch

from transformers import (
    AutoFeatureExtractor,
    ASTForAudioClassification,
    Wav2Vec2Processor,
    Wav2Vec2Model,
)

"""### Mount Drive and Load Prepared Data
This section mounts Google Drive to access stored data and then loads pre-processed audio splits (`X_train`, `y_train`, etc.) from a `joblib` file. These splits contain file paths to audio samples and their corresponding labels, ready for feature extraction and model training.
"""

from google.colab import drive
drive.mount('/content/drive')

data = joblib.load("/content/drive/MyDrive/Final Project RMOT/artifacts/processed/processed_audio_splits.joblib")

X_train = data["X_train"]
y_train = data["y_train"]

X_val = data["X_val"]
y_val = data["y_val"]

X_test = data["X_test"]
y_test = data["y_test"]

"""### Define Constants
This cell defines various constants used throughout the notebook, such as `RANDOM_STATE` for reproducibility, `SAMPLE_RATE` for audio processing, `CLIP_SECONDS` for audio segment length, `N_MELS` for mel-spectrogram generation, and batch sizes for training and embedding extraction. It also detects whether a GPU (`cuda`) or CPU is available for computation.
"""

RANDOM_STATE = 42
SAMPLE_RATE = 16000
CLIP_SECONDS = 5
N_MELS = 64
TF_BATCH_SIZE = 32
EMBEDDING_BATCH_SIZE = 4
CNN_EPOCHS = 5

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

"""### Audio Preprocessing Functions
- `load_waveform`: Loads an audio file and pads/trims it to a fixed duration.

"""

def load_waveform(path, sr=SAMPLE_RATE, seconds=CLIP_SECONDS):
    """Load one audio file, then pad or trim it to a fixed length."""
    audio, _ = librosa.load(path, sr=sr)
    target_len = sr * seconds

    if len(audio) < target_len:
        audio = np.pad(audio, (0, target_len - len(audio)))
    else:
        audio = audio[:target_len]

    return audio.astype(np.float32)

"""### Acoustic Spectrogram Transformer (AST) Feature Extraction
This section defines and executes the `extract_ast_features` function. This function utilizes a pre-trained AST model from Hugging Face Transformers to extract high-level features from audio waveforms. It processes audio in batches, leveraging the `AutoFeatureExtractor` and `ASTForAudioClassification` models, and computes the mean of the last hidden states as features. The extracted features for training, validation, and test sets are then printed.
"""

def extract_ast_features(paths, batch_size=EMBEDDING_BATCH_SIZE):
    feature_extractor = AutoFeatureExtractor.from_pretrained(
        "MIT/ast-finetuned-audioset-10-10-0.4593"
    )
    ast_model = ASTForAudioClassification.from_pretrained(
        "MIT/ast-finetuned-audioset-10-10-0.4593"
    ).to(device)
    ast_model.eval()

    features = []

    for start_idx in range(0, len(paths), batch_size):
        batch_paths = paths[start_idx:start_idx + batch_size]
        batch_audio = [load_waveform(path) for path in batch_paths]

        inputs = feature_extractor(
            batch_audio,
            sampling_rate=SAMPLE_RATE,
            return_tensors="pt",
        )
        inputs = {key: value.to(device) for key, value in inputs.items()}

        with torch.no_grad():
            outputs = ast_model(**inputs, output_hidden_states=True)
            hidden_states = outputs.hidden_states[-1]
            batch_features = hidden_states.mean(dim=1).detach().cpu().numpy()

        features.append(batch_features)

    return np.vstack(features)


ast_start = time.time()
ast_train_features = extract_ast_features(X_train)
ast_val_features = extract_ast_features(X_val)
ast_test_features = extract_ast_features(X_test)

ast_train_time = time.time() - ast_start

print("AST feature shapes:", ast_train_features.shape, ast_val_features.shape, ast_test_features.shape)

"""### Wav2Vec2 Feature Extraction
Similar to the AST section, this block defines and executes the `extract_wav2vec_features` function. This function uses a pre-trained Wav2Vec2 model to extract audio features from raw waveforms. It uses `Wav2Vec2Processor` to prepare the audio and `Wav2Vec2Model` to obtain hidden states, which are then averaged to form the final features. The extracted features for training, validation, and test sets are printed along with the time taken for extraction.
"""

def extract_wav2vec_features(paths, batch_size=EMBEDDING_BATCH_SIZE):
    processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base")
    wav2vec_model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base").to(device)
    wav2vec_model.eval()

    features = []

    for start_idx in range(0, len(paths), batch_size):
        batch_paths = paths[start_idx:start_idx + batch_size]
        batch_audio = [load_waveform(path) for path in batch_paths]

        inputs = processor(
            batch_audio,
            sampling_rate=SAMPLE_RATE,
            return_tensors="pt",
            padding=True,
        )

        input_values = inputs.input_values.to(device)
        attention_mask = (
            inputs.attention_mask.to(device)
            if hasattr(inputs, "attention_mask")
            else None
        )

        with torch.no_grad():
            outputs = wav2vec_model(
                input_values=input_values,
                attention_mask=attention_mask,
            )
            hidden_states = outputs.last_hidden_state
            batch_features = hidden_states.mean(dim=1).detach().cpu().numpy()

        features.append(batch_features)

    return np.vstack(features)


wav2vec_start = time.time()
wav2vec_train_features = extract_wav2vec_features(X_train)
wav2vec_val_features = extract_wav2vec_features(X_val)
wav2vec_test_features = extract_wav2vec_features(X_test)

wav2vec_train_time = time.time() - wav2vec_start

print("Wav2Vec2 feature shapes:", wav2vec_train_features.shape, wav2vec_val_features.shape, wav2vec_test_features.shape)

"""### Save Extracted Features
This section saves the extracted AST and Wav2Vec2 features, into *two separate `joblib` files*. The labels are also saved into a `joblib` file. This allows for persistent storage of these processed features, enabling their reuse in subsequent machine learning model training without re-running the feature extraction process.
"""

ast_feature_data = {
    "ast_train_features": ast_train_features,
    "ast_val_features": ast_val_features,
    "ast_test_features": ast_test_features
}

joblib.dump(ast_feature_data, "/content/drive/MyDrive/Final Project RMOT/artifacts/processed/extracted_ast_features.joblib")
print("Extracted AST features saved to /content/drive/MyDrive/Final Project RMOT/artifacts/processed/extracted_ast_features.joblib")

wav2vec_feature_data = {
    "wav2vec_train_features": wav2vec_train_features,
    "wav2vec_val_features": wav2vec_val_features,
    "wav2vec_test_features": wav2vec_test_features,

}

joblib.dump(wav2vec_feature_data, "/content/drive/MyDrive/Final Project RMOT/artifacts/processed/extracted_wav2vec_features.joblib")
print("Extracted Wav2Vec2 features saved to /content/drive/MyDrive/Final Project RMOT/artifacts/processed/extracted_wav2vec_features.joblib")

labels = {
    "train": y_train,
    "val": y_val,
    "test": y_test
}

joblib.dump(labels, "/content/drive/MyDrive/Final Project RMOT/artifacts/processed/labels.joblib")
print("Labels saved to /content/drive/MyDrive/Final Project RMOT/artifacts/processed/labels.joblib")