# -*- coding: utf-8 -*-
"""03_train_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzTBWuLjrvUQd2118pP8c3_4ELcDLunt

#Model Training

This notebook uses the audio features extracted and trains different anomaly detection models.

###Mounting Google Drive
"""

from google.colab import drive
drive.flush_and_unmount()

from google.colab import drive
drive.mount('/content/drive')

"""###Importing Extracted Features"""

import sys
import joblib

sys.path.append('/content/drive/MyDrive/Final Project RMOT/artifacts/processed')
sys.path.append('/content/drive/MyDrive/Final Project RMOT/artifacts/models')

import os
print(os.path.exists('/content/drive/MyDrive/Final Project RMOT/artifacts/models/models.py'))

try:
    wav2vec_features = joblib.load('/content/drive/MyDrive/Final Project RMOT(1)/artifacts/processed/extracted_wav2vec_features.joblib')
    print("The wav2vec features file loaded successfully.")
except FileNotFoundError:
    print("Error: The Wav2vec features file was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the joblib file: {e}")

try:
    ast_features = joblib.load('/content/drive/MyDrive/Final Project RMOT/artifacts/processed/extracted_ast_features.joblib')
    print("Ast features file loaded successfully.")
except FileNotFoundError:
    print("Error: The Ast features file was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the joblib file: {e}")

logmel_features = joblib.load('/content/drive/MyDrive/Final Project RMOT/artifacts/processed/extracted_logmel_features.joblib')

try:
    labels = joblib.load('/content/drive/MyDrive/Final Project RMOT/artifacts/processed/labels.joblib')
    print("labels file loaded successfully.")
except FileNotFoundError:
    print("Error: The labels file was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the joblib file: {e}")

"""###Importing Models"""

from models import get_ocsvm, get_isolation_forest, train_model, predict_model, get_anomaly_scores, build_cnn_model,     build_teacher_student_models,     train_teacher_student, predict_teacher_student


from sklearn.metrics import classification_report, accuracy_score, roc_auc_score
import os
import numpy as np
import pandas as pd

y_train = labels["train"]
y_val = labels["val"]
y_test = labels["test"]

"""###Experimental

We are going to add all our feature extractions and models into seperate dictionary so we can pick which features we want to train each model on.
"""

features = {
    "wav2vec" : wav2vec_features,
    "ast" : ast_features
}

models = {
    "ocsvm" : get_ocsvm(nu=0.1),
    "iso_forest" : get_isolation_forest(n_estimators=100, contamination=0.1)
}

"""In this cell change the features or model."""

SELECTED_FEATURES = ["wav2vec", "ast", "logmel"]
SELECTED_MODELS = ["ocsvm", "iso_forest", "teacher_student", "cnn"]

import numpy as np
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score

results = {}
y_train_np = np.array(y_train)
normal_mask = (y_train_np == 0)

for feature_name in SELECTED_FEATURES:
    X_train_data = features[feature_name][f'{feature_name}_train_features']
    X_val_data = features[feature_name][f'{feature_name}_val_features']
    X_test_data = features[feature_name][f'{feature_name}_test_features']

    results[feature_name] = {}

    X_train_normal = X_train_data[normal_mask]

    for model_name in SELECTED_MODELS:
        print(f"\nTraining {model_name} on {feature_name}...")

        model = models[model_name]
        model = train_model(model, X_train_normal)

        preds = predict_model(model, X_test_data)
        preds = np.array([0 if p == 1 else 1 for p in preds])

        assert len(preds) == len(y_test)

        report = classification_report(
            y_test,
            preds,
            target_names=["Normal", "Anomaly"],
            output_dict=True,
            zero_division=0
        )

        acc = accuracy_score(y_test, preds)

        try:
            scores = model.decision_function(X_test_data)

            # invert scores → higher = more anomalous
            # scores = -scores

            auc = roc_auc_score(y_test, scores)
        except:
            auc = None

        results[feature_name][model_name] = {
            "accuracy": acc,
            "precision": report["Anomaly"]["precision"],
            "recall": report["Anomaly"]["recall"],
            "f1": report["Anomaly"]["f1-score"],
            "auc": auc
        }

        print(f"Accuracy: {acc:.3f}, F1: {report['Anomaly']['f1-score']:.3f}, AUC: {auc}")

if "teacher_student" in SELECTED_MODELS and "logmel" in features:
    X_train = features["logmel"]["logmel_train_features"]
    X_test = features["logmel"]["logmel_test_features"]

    X_train_flat = X_train.reshape(len(X_train), -1)
    X_test_flat = X_test.reshape(len(X_test), -1)

    X_train_normal = X_train_flat[normal_mask]

    teacher, student = build_teacher_student_models(input_dim=X_train_flat.shape[1])
    student = train_teacher_student(
        teacher,
        student,
        X_train_normal,
        epochs=10,
        batch_size=32
    )

    preds, scores, threshold = predict_teacher_student(
        teacher,
        student,
        X_train_normal,
        X_test_flat
    )

    results.setdefault("logmel", {})
    results["logmel"]["teacher_student"] = {
        "accuracy": accuracy_score(y_test, preds),
        "auc": roc_auc_score(y_test, scores),
        "report": classification_report(y_test, preds, output_dict=True, zero_division=0),
        "threshold": threshold
    }

if "cnn" in SELECTED_MODELS and "logmel" in features:
    X_train = features["logmel"]["logmel_train_features"]
    X_val = features["logmel"]["logmel_val_features"]
    X_test = features["logmel"]["logmel_test_features"]

    # add channel dimension if needed
    if len(X_train.shape) == 3:
        X_train = X_train[..., np.newaxis]
        X_val = X_val[..., np.newaxis]
        X_test = X_test[..., np.newaxis]

    cnn_model = build_cnn_model(input_shape=X_train.shape[1:])

    cnn_model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=10,
        batch_size=32,
        verbose=1
    )

    probs = cnn_model.predict(X_test).ravel()
    preds = (probs >= 0.5).astype(int)

    results.setdefault("logmel", {})
    results["logmel"]["cnn"] = {
        "accuracy": accuracy_score(y_test, preds),
        "auc": roc_auc_score(y_test, probs),
        "report": classification_report(y_test, preds, output_dict=True, zero_division=0)
    }

"""### Saving Model Results"""

import pandas as pd
from datetime import datetime
import os

current_date = datetime.now().strftime("%Y-%m-%d")

results_dir = '/content/drive/MyDrive/Final Project RMOT/artifacts/results'
os.makedirs(results_dir, exist_ok=True)

all_results_data = []

for feature_name, model_results in results.items():
    for model_name, metrics in model_results.items():
        row = {
            'date': current_date,
            'feature_type': feature_name,
            'model_trained': model_name,
            'accuracy': metrics.get('accuracy'),
            'precision': metrics.get('precision'),
            'recall': metrics.get('recall'),
            'f1_score': metrics.get('f1'),
            'auc': metrics.get('auc')
        }
        all_results_data.append(row)

df_results = pd.DataFrame(all_results_data)

results_filename = os.path.join(results_dir, f"model_training_results_{current_date}.csv")
df_results.to_csv(results_filename, index=False)

print(f"Model training results saved to: {results_filename}")
display(df_results)